[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.24",
    "langchain-ollama>=0.3.2",
    "python-dotenv>=1.1.0",
]
